In [3]:
#To know shape of the array
import numpy as np 
array=np.array([[1,2,3],[5,4,8]])
print(array)
print(array.shape)

[[1 2 3]
 [5 4 8]]
(2, 3)


In [4]:
#To know size of the array
import numpy as np 
array=np.array([[1,2,3],[5,4,8]])
print(array)
print(array.size)

[[1 2 3]
 [5 4 8]]
6


In [6]:
#To know symention of the array
import numpy as np 
array1=np.array([1,2,3])
array2=np.array([[1,2,3],[5,4,8]])
array3=np.array([[[1,2,3],[5,4,8],[7,8,9]]])

print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


In [7]:
#To check the datatype of the array
import numpy as np 
array=np.array([[1,2,3],[5,4,8]])
print(array)
print(array.dtype)

[[1 2 3]
 [5 4 8]]
int64


In [8]:
#To change the datatype of the array
import numpy as np 
array=np.array([1.2,2.5,8.9])
int_arr=array.astype(int)
print(int_arr)
print(int_arr.dtype)

[1 2 8]
int64
