In [4]:
#Insert Elements
import numpy as np 
arr=np.array([10,20,30,40,50])
new_arr=np.insert(arr,2,100,axis=None)
print(new_arr)
print(arr)

arr2d=np.array([[10,20],[30,40]])
new_arr2D=np.insert(arr2d,[1,1],100,axis=0)
print(new_arr2D)
print(arr2d)

[ 10  20 100  30  40  50]
[10 20 30 40 50]
[[ 10  20]
 [100 100]
 [100 100]
 [ 30  40]]
[[10 20]
 [30 40]]


In [5]:
#Append
import numpy as np 
arr=np.array([10,20,30,40,50])
new_arr=np.append(arr,[60,100])
print(new_arr)
print(arr)

[ 10  20  30  40  50  60 100]
[10 20 30 40 50]


In [7]:
#Concatenate
import numpy as np 
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,100])
new_arr=np.concatenate((arr1,arr2))
print(new_arr)

arr2d1=np.array([[10,20],[30,40]])
arr2d2=np.array([[70,80],[90,50]])
new_arr=np.concatenate((arr2d1,arr2d2),axis=1)
print(new_arr)



[ 10  20  30  40  50  60 100]
[[10 20 70 80]
 [30 40 90 50]]


In [9]:
#Delete
import numpy as np 
arr=np.array([10,20,30,40,50])
new_arr=np.delete(arr,2,axis=None)
print(new_arr)

[10 20 40 50]
