In [ ]:
#Vectorization_AND_Broadcasting
import numpy as np
arr=np.array([400,500,600,900])
disc=10
price=arr-(arr*disc/100)
print(price)

[360. 450. 540. 810.]


In [2]:
#1D to 2D Broadcasting
import numpy as np

arr_2D=np.array([[1,2,3],[4,5,6]])
arr_1D=np.array([10,20,30])
result=arr_2D+arr_1D
print(result)

[[11 22 33]
 [14 25 36]]


In [3]:
import numpy as np

arr_2D=np.array([[1,2,3],[4,5,6]])
print(arr_2D*10)

[[10 20 30]
 [40 50 60]]
