In [8]:
import numpy as np

In [16]:
#creating numpy array directly

a=np.array([1,7,8,9,6,3,4])
print(a)
print(type(a))
print(a.ndim)


[1 7 8 9 6 3 4]
<class 'numpy.ndarray'>
1


In [17]:
l=[]

for i in range(1,6):
    el=int(input("Enter the number: "))
    l.append(el)
y=np.array(l)
print(y)
print(y.ndim)

[14 15 16 18 17]
1


In [23]:
arr2=np.array([[1,2,5,4],[1,4,5,8],[7,8,9,6]])
print(arr2)
print(arr2.ndim)

[[1 2 5 4]
 [1 4 5 8]
 [7 8 9 6]]
2


In [21]:
arr3=np.array([[[1,2,5,4],[1,4,5,8],[7,8,9,6]]])
print(arr3)
print(arr3.ndim)

[[[1 2 5 4]
  [1 4 5 8]
  [7 8 9 6]]]
3


In [27]:
arn=np.array([1,8,6,7],ndmin=10)
print(arn)
print(type(arn))
print(arn.ndim)

[[[[[[[[[[1 8 6 7]]]]]]]]]]
<class 'numpy.ndarray'>
10
