In [ ]:
#Indexing
import numpy as np 
arr_1D=np.array([10,20,30,40,50,60])
print(arr_1D[4])

arr_2D=np.array([[1,20,90],[40,80,50]])
print(arr_2D[1,2])



50
50


In [ ]:
#Slicing
import numpy as np 
arr=np.array([12,14,16,18,20,22,24])
print(arr[1:7:2])
print(arr[:5:1])
print(arr[::2])
print(arr[::-1])

[14 18 22]
[12 14 16 18 20]
[12 16 20 24]
[24 22 20 18 16 14 12]


In [13]:
#Fancy Indexing
import numpy as np 
arr=np.array([12,14,16,18,20,22,24])
print(arr[[1,2,6]])


[14 16 24]


In [16]:
#Boolean Masking
import numpy as np 
arr=np.array([12,14,16,18,20,22,24,30,40])
print(arr[25<arr])

[30 40]
