In [1]:
import numpy as np

In [4]:
arr1=np.random.rand(4)
print(arr1)
print(" ")

arr2=np.random.rand(3,4)
print(arr2)

[0.41759789 0.29141471 0.97468639 0.6091693 ]
 
[[0.32743858 0.13890612 0.08221736 0.21868905]
 [0.74710614 0.7685082  0.54903695 0.68557749]
 [0.46975703 0.37396621 0.68160303 0.11860395]]


In [7]:
array=np.random.randn(5)
print(array)
print(" ")

array1=np.random.randn(3,4)
print(array1)

[-0.03504793  0.53521541  0.35048152  0.70540312 -0.68700677]
 
[[-0.07113628  0.05803993 -0.35353517 -0.70807479]
 [-0.31039246 -0.49354909  1.17726409  0.2106785 ]
 [ 0.00979699 -0.98928966 -0.4090434  -0.68375329]]


In [11]:
array3=np.random.ranf(5)
print(array3)
print(" ")

array4=np.random.ranf((3,5))
print(array4)

[0.14548987 0.85303462 0.21777999 0.25203075 0.41564985]
 
[[0.65029512 0.36174993 0.35863662 0.9858298  0.20028914]
 [0.56819131 0.55671405 0.11655975 0.44273693 0.8496046 ]
 [0.58748846 0.36092331 0.00744503 0.81758054 0.89966791]]
