In [4]:
import numpy as np 

array=np.array([1,2,5,4,6])
print(array+2)
print(array-2)
print(array*2)
print(array/2)
print(array//2)
print(array**2)
print(array%2)


[3 4 7 6 8]
[-1  0  3  2  4]
[ 2  4 10  8 12]
[0.5 1.  2.5 2.  3. ]
[0 1 2 2 3]
[ 1  4 25 16 36]
[1 0 1 0 0]
