In [ ]:
#Reshaping
import numpy as np 
arr_1D=np.array([10,20,30,40,50,60])
arr_2D=arr_1D.reshape(2,3)
print(arr_2D)

[[10 20 30]
 [40 50 60]]


In [2]:
#Flattening
import numpy as np 
arr=np.array([[[1,2,3],[3,4,5],[5,6,7]]])
print(arr.ravel())
print(arr.flatten())

[1 2 3 3 4 5 5 6 7]
[1 2 3 3 4 5 5 6 7]
