In [1]:
import numpy as np

In [5]:
#Creating Numpy array with zeros

#1D
arr_zero=np.zeros(4)
print(arr_zero)
print(" ")

#More than 1D
arr_zero1=np.zeros((3,4))
print(arr_zero1)

[0. 0. 0. 0.]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
