In [1]:
#Array filled with zeros
import numpy as np 
array_zeros=np.zeros((3,4))
print(array_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Array filled with ones
import numpy as np 
array_ones=np.ones((4,4))
print(array_ones)

[1. 1.]


In [4]:
#An array with a specific range or sequence of elements
import numpy as np 
array_range=np.arange(1,10,2)
print(array_range)

[1 3 5 7 9]


In [6]:
#For creating a empty array
import numpy as np 
empty_array=np.empty(5)
print(empty_array)

[0.00000000e+000 8.10729178e-312 8.10729176e-312 8.10729177e-312
 1.06099790e-314]


In [9]:
#An array for diagonal amtrix or identity matrix
import numpy as np
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#Array with a specific element
import numpy as np 
specific_array=np.full((3,5),7)
print(specific_array)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
