In [1]:
import numpy as np

In [5]:
#Creating Numpy array with zeros

#1D
arr_zero=np.zeros(4)
print(arr_zero)
print(" ")

#More than 1D
arr_zero1=np.zeros((3,4))
print(arr_zero1)

[0. 0. 0. 0.]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#Creating Numoy array with ones

#1D
arr_one=np.ones(4)
print(arr_one)
print(" ")

#More than 1D
arr_one1=np.ones((4,3))
print(arr_one1)

[1. 1. 1. 1.]
 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#Creating Empty Array
arr_empt=np.empty(4)
print(arr_empt)

[1. 1. 1. 1.]
